language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  slack: uglybugdesign:x1lPUImO8LcTWRbMgPtqvLeE

before_install:
  - pip install --user codecov

after_success:
  - codecov
